name: Release

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm build

      - name: Create Firefox zip
        run: |
          cd dist
          mv firefox.zip ../firefox.zip
          cd ..

      - name: Create Chrome zip
        run: |
          cd dist
          zip -r ../chrome.zip .
          cd ..

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: main
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            firefox.zip
            chrome.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
