name: Sync main to v2 branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Sync with v2 branch
        run: |
          git fetch origin v2
          git checkout v2
          git reset --hard main
          git push -f
